# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
title:            QuickScythe
tagline:          'blog'
description:      'My personal blog.'
url:              http://quickscythe.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name: 'Cameron Witcher'

paginate: 5

# Custom vars
icon: /assets/images/icon2.png
cover: /assets/images/menu-background.png

social:
  - icon: twitter
    url: https://twitter.com/quickscythe
    desc: Follow me on Twitter
  - icon: github
    url: https://github.com/QuickScythe
    desc: Fork me on GitHub

  - icon: googleplus-alt
    url: https://google.com/+QuickScythe
    desc: Follow me on google+
    
menu:
  - title: Home
    url: /
    
  - title: About
    url: /about
    
  - title: Resumé
    url: /resume


copyright:
  author: Cameron Witcher
  url: http://quickscythe.github.io
  type_title: Some rights reserved.
  type_url: http://creativecommons.org/licenses/by-nc/2.5/br
